digitalrebar/provision-plugins

cmds/bios/bios.go
cmds/callback/callback.go
cmds/certs/certs.go
cmds/eikon/eikon.go
cmds/filebeat/filebeat.go
cmds/honeycomb/honeycomb.go
cmds/image-deploy/image-deploy.go
cmds/ipmi/main.go
cmds/kvm-test/kvm-test.go
cmds/netbox/netbox.go
cmds/ovirt/ovirt.go
cmds/packet-ipmi/packet-ipmi.go
cmds/raid/raid.go
cmds/slack/slack.go
cmds/tower/tower.go
cmds/virtualbox-ipmi/virtualbox-ipmi.go
cmds/vmware/vmware.go
go.mod
go.sum

Also, update provision to latest prerelease version.

Bump plugin version for all plugins

---

cmds/vmware/content/params/esxi-disk-install-override-custom.yaml
cmds/vmware/content/params/esxi-disk-install-override.yaml
cmds/vmware/content/params/esxi-ks-custom-kickstart.yaml
cmds/vmware/content/params/esxi-ks-custom-sections.yaml
cmds/vmware/content/params/esxi-network-firstboot-type.yaml
cmds/vmware/content/params/esxi-network-firstboot-vlan.yaml
cmds/vmware/content/params/esxi-network-kickstart-type.yaml
cmds/vmware/content/params/esxi-network-kickstart-vlan.yaml
cmds/vmware/content/params/esxi-serial-console.yaml
cmds/vmware/content/params/esxi-skip-tools.yaml
cmds/vmware/content/params/vmware-esxi-hcl-validated.yaml
cmds/vmware/content/stages/in-subnet-check-render.yaml
cmds/vmware/content/tasks/in-subnet-check-validate.yaml

Sigh.  I seem to reflexively type "insure" when it's "ensure".  I know this.  But my fingers don't.  Try to fix all the places.

fix insure to ensure

---

cmds/vmware/content/templates/esxi-network-firstboot.tmpl

- removes all DNS servers if DNS Servers array is set, prior to adding new DNS servers

fix DNS servers to remove Weasel/DHCP added, only use specified

---

cmds/vmware/download-vibs.sh

Update the drpy vib to see if we can reboot cleanly

---

cmds/ipmi/content/tasks/ipmi-network-validation.yaml

task that will check the network validation using:
ipmi/configure/address
ipmi/configure/gateway
ipmi/configure/netmask

Added ipmi network validation task

---

cmds/vmware/content/._Documentation.meta

* note on selector needs run in sledgehammer
* add Patching overview documentation
* remove "extra kickstart ideas" section
* add Agent/Runner overview information
* add `vmk0` error information

Cleanup overview documentation elements

---

cmds/vmware/content/tasks/vmware-selector.yaml

- fix errant double quote in the NEC selector case statement

Fix NEC selector selection

---

cmds/callback/callback.go

callback/override-data allows for data to be sent instead of the machine

WIP - Allow callers to override the data pushed to the callback. - needs testing.

---

cmds/vmware/content/tasks/esxi-patch-complete.yaml
cmds/vmware/content/tasks/esxi-patch-start.yaml
cmds/vmware/download-vibs.sh

Update the drpy vib and put back the esxi-patch-* tasks

---

cmds/vmware/content/params/esxi-rename-datastore.yaml
cmds/vmware/content/stages/esxi-rename-datastore.yaml
cmds/vmware/content/tasks/esxi-rename-datastore.yaml

- adds stage/task to rename datastore1
- sets `esxi/install-datastore` if rename is successful

Add esxi/rename-datastore stage/task

---

cmds/vmware/content/workflows/esxi-install.yaml

Adds the esxi-rename-datastore task to the esxi-install WF

Add rename datastore to esxi-install WF

---

cmds/vmware/content/._Documentation.meta

this allows the FAQ password section to link directly to this section.

add doc ref link

---

cmds/vmware/content/tasks/esxi-set-network.yaml

for firstboot actions.  Specifically MTU

The VKM0 setting is not right, but might not matter because switch.

---

cmds/vmware/content/templates/esxi-install-py3.ks.tmpl

We were appending when we should have been making new.

fixing issue where there are 2 instances of drpy

---

cmds/vmware/content/templates/esxi-drpy-run.py.tmpl
cmds/vmware/content/templates/esxi-drpy-vib-render.py.tmpl
cmds/vmware/download-vibs.sh

Stil requires /etc/rc.local.d/local.sh

Try to install DRPY independent of backing stores.

---

cmds/raid/drp-raid/volspec.go

Fixes digitalrebar/provision #101.

Make minimal structures for volspecs.

---

cmds/raid/content/tasks/raid-tools-install.yml

fix(raid): fix internal perccli bundle extraction.

---

cmds/raid/content/params/raid-archive-urls.yaml
cmds/raid/content/tasks/raid-tools-install.yml
cmds/raid/drp-raid/main.go
cmds/raid/drp-raid/mvcli.go
cmds/raid/drp-raid/pd.go
cmds/raid/drp-raid/perccli.go

To increase perccli support, we would need a better controller.

feat(raid): Add support for mvcli and perccli.  Perccli is partial.

---

cmds/vmware/content/._Documentation.meta
cmds/vmware/content/bootenvs/esxi-550u3b.yaml
cmds/vmware/content/bootenvs/esxi-6.7.0-update1-10302608-custom-hitachi_0200_Blade_HA8000.yaml
cmds/vmware/content/bootenvs/esxi-6.7.0-update1-10302608-custom-hitachi_1200_HA8000VGen10.yaml
cmds/vmware/content/bootenvs/esxi-6.7.1-10302608-nec-6.702.yaml
cmds/vmware/content/bootenvs/esxi-6.7.1-10302608-nec-gen-6.7.yaml
cmds/vmware/content/bootenvs/esxi-600u2.yaml
cmds/vmware/content/bootenvs/esxi-600u3a.yaml
cmds/vmware/content/bootenvs/esxi-650a.yaml
cmds/vmware/content/bootenvs/esxi-650u2.yaml
cmds/vmware/content/bootenvs/esxi-670.yaml
cmds/vmware/content/bootenvs/esxi-670u2.yaml
cmds/vmware/content/bootenvs/esxi-dellemc-esxi-6.7u1-10764712-a04.yaml
cmds/vmware/content/bootenvs/esxi-fujitsu-vmvisor-installer-6.7-10.yaml
cmds/vmware/content/bootenvs/esxi-hpe-esxi-6.7.0-update1-iso-gen9p.yaml
cmds/vmware/content/bootenvs/esxi-lenovo_esxi6.7u1-10302608_201810.yaml
cmds/vmware/content/bootenvs/esxi-vmware-esxi-6.7.0-10302608-custom-cisco.yaml
cmds/vmware/content/params/esxi-disk-install-override-custom.yaml
cmds/vmware/content/params/esxi-drp-port-disable.yaml
cmds/vmware/content/params/esxi-password-policy.yaml
cmds/vmware/content/params/passgen-settings.yaml
cmds/vmware/content/params/vmware-esxi-version-override.yaml
cmds/vmware/content/stages/in-subnet-check-validate.yaml

minor vmware plugin docs changes

---

cmds/raid/content/params/raid-available-utilities.yaml
cmds/raid/content/params/raid-current-config.yaml
cmds/raid/content/params/raid.encryption-password-save.yml
cmds/raid/content/tasks/raid-enable-encryption.yml

Waiting on this until we know we should store this password.

Save encryption password on machine in case it is needed.

---

cmds/vmware/content/params/esxi-disk-install-options.yaml
cmds/vmware/content/params/esxi-network-firstboot-vlan-vm-network.yaml
cmds/vmware/content/params/esxi-network-firstboot-vlan.yaml
cmds/vmware/content/params/esxi-network-kickstart-vlan.yaml

- fix various minor doc RST format nits

docs(vmware): Fix more doc validation errors.

---

cmds/callback/content/._Documentation.meta

- add section on Data Override
- add Example section using the `Postman-Echo` scenario

doc(callback): Enhance and add examples to Callback Plugin doc

---

cmds/image-deploy/content/._Documentation.meta
cmds/image-deploy/content/stages/image-deploy-cloud-init.yaml
cmds/image-deploy/content/stages/image-deploy.yaml
cmds/image-deploy/content/workflows/image-deploy-base.yaml

To help new operators understand first steps, create a basic reference workflow for image install.

refactor(plugin image-deploy): add reference workflow

---

cmds/bios/content/._Documentation.meta

- adds reference link to the Operations document

enhance(bios): Add BIOS Ops doc link to Overview doc

---

cmds/image-deploy/content/params/image-deploy.image-type.yaml

- enhance doc field on `image-deploy/image-type` to list supported types

enhance(image-deploy): Add more info to 'image-deploy/image-type' Doc field

---

cmds/vmware/content/params/esxi-bundles-6.yaml
cmds/vmware/content/params/esxi-bundles-7.yaml
cmds/vmware/content/params/esxi-rackn-bundles-6.yaml
cmds/vmware/content/params/esxi-rackn-bundles-7.yaml
cmds/vmware/content/stages/vmware-build-isos.yaml
cmds/vmware/content/tasks/vmware-get-bundles.yaml
cmds/vmware/content/tasks/vmware-iso-build.yaml
cmds/vmware/content/tasks/vmware-powershell-install.yaml
cmds/vmware/content/tasks/vmware-push-isos.yaml
cmds/vmware/content/workflows/esxi-build-isos.yaml

This provides parameters, stages, tasks, and workflow for
building vmware isos with RackN bundles on top of a windows10
image-deployed system.

feat(vmware): initial pass automated vmware iso builder

---

cmds/ipmi/content/._Description.meta
cmds/ipmi/content/._DisplayName.meta
cmds/ipmi/content/._Documentation.meta

addressing confusion about IPMI because it's not limited to IPMI anymore

doc(ipmi-plugins): make it clearer that IPMI is not just IPMI

---

cmds/ipmi/content/params/ipmi.address-v4.yaml
cmds/ipmi/content/params/ipmi.address-v6.yaml
cmds/ipmi/content/params/ipmi.gateway-v6.yaml
cmds/ipmi/content/params/ipmi.ipsrc-v4.yaml
cmds/ipmi/content/params/ipmi.ipsrc-v6.yaml
cmds/ipmi/content/params/ipmi.netmask-v4.yaml
cmds/ipmi/content/params/ipmi.netmask-v6.yaml
cmds/ipmi/content/params/ipmi.port-ipmitool.yaml
cmds/ipmi/content/params/ipmi.port-redfish.yaml
cmds/ipmi/content/params/ipmi.prefer-v6.yaml
cmds/ipmi/content/templates/ipmi-inventory.sh.tmpl
cmds/ipmi/racadm.go
cmds/ipmi/redfish.go

This only adds inventory support along with params to control
what address to prefer in the case that both are valid.

feat(ipmi-ipv6): Add ipv6 inventory for ipmi controllers.

---

cmds/vmware/content/stages/esxi-join-local.yaml
cmds/vmware/content/tasks/no-op.yaml
cmds/vmware/content/workflows/esxi-join-local.yaml

This change adds support for the esxi-join-up.py
Related: digitalrebar/provision-content#703

feat(vmware): added workflow to support esxi-join

---

cmds/image-deploy/content/params/image-deploy.image-os.yaml
cmds/image-deploy/content/tasks/cloud-init-wait.yaml
cmds/image-deploy/content/tasks/curtin-deploy.yaml
cmds/image-deploy/content/templates/curtin-drpy-agent.conf.tmpl
cmds/image-deploy/content/templates/curtin-esxi-curtin-hooks.py.tmpl
cmds/image-deploy/content/templates/curtin-install.sh.tmpl

Add image-deploy capabilities for vSphere ESXi systems.

(WIP) enhance(image-deploy): Add ESXi image deployment capabilities

---

cmds/image-deploy/content/tasks/curtin-deploy.yaml
cmds/image-deploy/content/templates/curtin-esxi-network-startup.sh.tmpl

DRPY startup will attempt to call it.

feat(image-deploy): add esxi network script (empty)

---

cmds/filebeat/content/profiles/bootstrap-filebeat.yaml
cmds/vmware/content/params/esxi-drpy-log-level.yaml

minor update limits inputs to enum

refactor(provision-plugins): use enum to limit values

---

cmds/vmware/content/params/esxi-enable-legacy-install.yaml
cmds/vmware/content/templates/esxi-install-py3-default.ks.tmpl
cmds/vmware/content/templates/esxi-install-py3-legacy.ks.tmpl
cmds/vmware/content/templates/esxi-install-py3.ks.tmpl
cmds/vmware/content/templates/esxi-render-firewall-vib.py.tmpl
cmds/vmware/content/templates/esxi-vib-common.py.tmpl
cmds/vmware/download-vibs.sh
cmds/vmware/embedded/scripts/make-esxi.sh
cmds/vmware/vmware.go

Adds support to the vmware plugin to allow for the legacy style of installs via firtstboot

feat(vmware): added support to allow legacy drpy

---

cmds/vmware/content/params/esxi-set-network-protocol.yaml

Removed the false info from a copy/pasta

doc(esxi-set-network-protocol): remove false info

---

cmds/bios/bioscfg/supermicro.go

Sadly, this is not complete BMC setting support -- making changes to a
few setting types requires more complicated differencing than what we
currently support in the bioscfg wrapper.

feat(supermicro): Add semi-functional BMC config support.

---

tools/build_hw_tool_repo.sh

The version that was in the repo was massively out-of-date with
respect to what vendors currently use.  Update it with current
tooling, and refactor to make it easier to keep up to date.

fix(hw_repo): Update build_hw_tool_repo.sh.

---

cmds/vmware/content/params/esxi-skip-disable-slpd-76372.yaml
cmds/vmware/content/stages/esxi-disable-slpd-76372.yaml
cmds/vmware/content/tasks/esxi-disable-slpd-76372.yaml
cmds/vmware/content/templates/esxi-disable-slpd-76372.sh.tmpl
cmds/vmware/content/workflows/esxi-install.yaml

Adds stage, task, template and param to esxi-install workflow to allow an operator to disable slpd per the vmware kb 76372

feat(vmware): disable slpd per vmware kb 76372
