digitalrebar/provision-plugins

cmds/vmware/download-vibs.sh

- switch from `curl` to `wget` - curl 404 but exit code 0 - so error handling harder
- add new environment variables to override getting VIBs:
+ `VIB_VERSION` - set the version to download
+ `VIB_BASE` - set the URL download base path to the VIB file
+ `VIB_FORCE` - (set to `true` to use) - forces getting files even if current versions exist
- (very) basic verification checks of the downloads

Enhance vib download

---

cmds/vmware/content/params/esxi-network-firstboot-vlan-vm-network.yaml
cmds/vmware/content/templates/esxi-network-firstboot.tmpl

Enables setting the `VM Network` VLAN to either a VLAN ID (1 to 4096) or to the value of `management` in which case it'll re-use the same VLAN ID associated for the `Management Network`.

add 'VM Network' portgroup VLAN setting

---

cmds/vmware/content/._Documentation.meta

Update `._Documentation.meta` with some common error messages that an operator may see during ESXi installation.  These errors are "to be expected", and can not (at this time) be removed from the installation process.

Document VMware install time errors

---

cmds/vmware/content/templates/esxi-network-firstboot.tmpl

- ntp start doesn't seem to reliably open FW ports - manually do this
- collect `ntpq -pn` output on peer status after 30 second delay

Ntp enhancements

---

cmds/vmware/content/tasks/validation-machine-name-dns-to-ip.yaml

added task to validate Machine.Name points to esxi/network-firstboot-ipaddr to the vmware plugin
This depends on https://github.com/digitalrebar/provision-content/pull/339

added task to validate firstboot-ipaddr in vmware

---

cmds/vmware/content/templates/in-subnet-check.sh.tmpl

Migrated the current in subnet validation script to use the new validation lib from the main
validation content pack

migrate the current in subnet shell to use lib

---

cmds/vmware/content/templates/vmware-esxi-selector.tmpl

* fixes VENDOR setting (esxi/selected-vendor) for non-`select-bootenv` types
* cleans up output logging
* adds red hat/kvm vendor type test
* removes default output of JSON object for task set - overridden by setting `rs-debug-enable` on

Fixups for 'VENDOR' param setting paths

---

cmds/endpoint-exec/content/params/endpoint-exec.parameters.yaml
cmds/endpoint-exec/content/tasks/endpoint-exec-task.yaml

command just work.  Also, use -- in parameter processing
as an example.

Default endpoint-exec parameters to empty string so that the

---

cmds/vmware/content/params/esxi-install-datastore.yaml

In the vmware content the esxi/install-datastore was improperly
labeled with a `password: showable` this change removes that
so that the value will not be hidden.

removes password setting from non password field

---

cmds/vmware/content/params/passgen-settings.yaml
cmds/vmware/content/templates/esxi-set-insecure-password.sh.tmpl
cmds/vmware/content/templates/passgen.py.tmpl

In the vmware passgen.py.tmpl it is now possible to pass in a `leading_char` and a `trailing_char` and if you dont a random lowercase letter is picked to be used in ita place. This change forces either the passed in chars or a random lower case for all passwords now.

Added random char to leading and trailing password

---

cmds/vmware/content/stages/esxi-install-patches.yaml
cmds/vmware/content/tasks/esxi-enable-maint-mode.yaml
cmds/vmware/content/tasks/esxi-exit-maint-mode.yaml

In the vmware content the esxi-patch-start and esxi-patch-complete tasks were poorly named. This change renamed those tasks to make it more obvious which part of the tasks put the host into and out of maint mode. This change should fix an issue that left the admin with no obvious reusable task to leave a host in maint mode.

rename vmware content patch bits

---

cmds/raid/content/tasks/raid-tools-install.yml

Fixes digitalrebar/provision#102

docs(raid): Fix link to storcli6.  Does not need .zip anymore.

---

cmds/vmware/content/tasks/esxi-install-welcome.yaml
cmds/vmware/content/tasks/esxi-patch-install.yaml
cmds/vmware/content/tasks/esxi-preserve-logs.yaml

improperly cased "TYPE" should have been "Type" causing errors in the welcome, patch, and preserve logs.

fixed case error in vmware plugin

---

cmds/ipmi/redfish.go

Supermicro Redfish API implementation does not return any available
values in the reset type field. However, it supports `ForceRestart`
but it does not support `PushPowerButton` that is the default
behaviour in the `fillForOn` and `fillForOff` functions.
To make the implementation work for the Supermicro implementation,
the default case has been changed to set the action to
`ForceRestart`. A new case for `PushPowerButton` has been added
so that systems stating that they support that functionality will
not see any change of behaviour.
Supermicro Redfish Guide p.21-22:
https://www.supermicro.com/manuals/other/RedfishRefGuide.pdf

Default behaviour when no reset type available

---

cmds/vmware/content/._Documentation.meta

* Documents the vSphere 7.0.0 tools.t00 "cannot open file" error message
* Occurs when `esxi/skip-tools` is set to `true` on ESXi 7.x
* ISO Manifest of modules can not be modified on the fly any more

docs(vmware): Add tools.t00 error message note

---

cmds/vmware/content/._Documentation.meta
cmds/vmware/content/tasks/esxi-activate-nesting.yaml
cmds/vmware/content/tasks/esxi-password-security-policy.yaml
cmds/vmware/content/tasks/esxi-rename-datastore.yaml
cmds/vmware/content/tasks/esxi-set-dns.yaml
cmds/vmware/content/tasks/esxi-set-hostname.yaml
cmds/vmware/content/tasks/esxi-set-network.yaml
cmds/vmware/content/tasks/esxi-set-ntp.yaml
cmds/vmware/content/tasks/in-subnet-check-render.yaml
cmds/vmware/content/tasks/in-subnet-check-validate.yaml
cmds/vmware/content/tasks/validation-machine-name-dns-to-ip.yaml
cmds/vmware/content/tasks/vmware-esxi-clear-patch-index.yaml
cmds/vmware/content/tasks/vmware-esxi-set-password.yaml
cmds/vmware/content/templates/esxi-acceptance-level.sh.tmpl
cmds/vmware/content/templates/esxi-disk-install-override.tmpl
cmds/vmware/content/templates/esxi-firewall-drp.tmpl
cmds/vmware/content/templates/esxi-install-py3.ks.tmpl
cmds/vmware/content/templates/esxi-install.ks.tmpl
cmds/vmware/content/templates/esxi-notify-drp-py3.tmpl
cmds/vmware/content/templates/esxi-notify-drp.tmpl
cmds/vmware/content/templates/vcf-builder-deploy.sh.tmpl
cmds/vmware/content/templates/vcf-builder-settings.sh.tmpl
cmds/vmware/content/templates/vcsa-deploy.sh.tmpl
cmds/vmware/content/workflows/vcf-builder-deploy.yaml

- fix minor spelling errors in content components
- add a few `Documentation` sections for missing pieces
- correct the header/title RST formatting strings to match correct generated doc formats

docs(vmware): Minor format and spelling fixes.

---

cmds/bios/content/._Documentation.meta
cmds/bios/content/params/bios-driver.yml
cmds/bios/content/params/bios-last-attempted-configuration.yml
cmds/bios/content/params/bios-skip-config.yaml
cmds/bios/content/params/bios-target-configuration.yml
cmds/bios/content/stages/bios-baseline.yml
cmds/bios/content/stages/bios-configure.yml
cmds/bios/content/tasks/bios-configure.yml
cmds/bios/content/tasks/bios-current-config.yml
cmds/bios/content/tasks/bios-set-baseline.yml
cmds/bios/content/tasks/bios-tools-install.yml

The BIOS plugin was bereft of documentation.  Added documentation
to the stages, tasks, and params provided by the BIOS plugin, along
with an introductory top-level doc bit.

docs(bios) Add documentation for params, stages, and tasks

---

cmds/vmware/content/params/esxi-skip-update-address.yaml
cmds/vmware/content/tasks/esxi-set-network.yaml

Added new parameter esxi/skip-update-address to control
whether the esxi-set-network task should update the
machine's address field to match the new address.
The default is true - don't do it.  Setting the parameter
to false will update the field.

feat(vmware): add task to update Machine Address field on network change

---

cmds/callback/callback.go
cmds/callback/content/._Documentation.meta
cmds/callback/content/params/callback.callbacks.yaml

callback/callbacks now has JsonResponse, StringResponse, and NoBody
flags.  This will alter the returns from base64 to json blob or raw
string.  It will also allow you to send NoBody.

feat(callback): add non-base64 options.

---

cmds/ipmi/content/templates/ipmi-configure.sh.tmpl

Some BMCs change values of gateway and netmask on the change
of dhcp to static mode.  If they do, the code has cached values
and may not fix the network settings.

fix(ipmi): regather lan info after changing dhcp to static.

---

cmds/vmware/content/templates/vmware-esxi-selector.tmpl

- adds enhanced checks for VMware bootenvs
- non-fatal check  if ISO is available - outputs appropriate message
- fatal media check if not available - this could either be the exploded ISO, or the static-lookaside location that resolves to the media

enhance(vmware): Add ISO and exploded Media availability checks.

---

cmds/ipmi/content/._Documentation.meta
cmds/ipmi/content/params/ipmi.mode.yaml
cmds/ipmi/content/params/ipmi.port-ipmitool.yaml
cmds/ipmi/content/params/ipmi.port-racadm.yaml
cmds/ipmi/content/params/ipmi.port-redfish.yaml
cmds/ipmi/ipmi.go
cmds/ipmi/main.go
cmds/ipmi/racadm.go
cmds/ipmi/redfish.go

- adds 3 new params to specify a network Port to define for `ipmitool`, `racadm`, and `redfish` mode of operation

enhance(ipmi): Add Port option for ipmitool, redfish, racadm

---

cmds/image-deploy/content/params/image-deploy.admin-password.yaml
cmds/image-deploy/content/params/image-deploy.admin-username.yaml
cmds/image-deploy/content/stages/image-deploy-cloud-init.yaml
cmds/image-deploy/content/templates/curtin-windows-cloudinit-finalize.tmpl

- set default values for `image-deploy/admin-username` and `...-password`
- add user/pass to `image-deploy-cloud-init` template
- fix metadata services for _unattend_ and regular _conf_ file
NOTE: The admin-username and password still do not seem to plumb in correctly.

enhance(image-deploy): Fixes for Windows deployments

---

cmds/kvm-test/libvirt.go

- removes the USB tablet device from the virtual machine spec
The tablet device shouldn't be necessary in most use cases, and it breaks on newer versions of libvirt machine models.

enhance(kvm-test): Remove 'tablet' type USB device

---

cmds/ipmi/content/._Prerequisites.meta

Fixes ipmi plugin has prereq on hardware-tooling task 'reset-bmc', but no ._Prerequisites.meta file reference

fix(ipmi): Add prerequisites on 'hardware-tooling' for 'reset-bmc' task

---

cmds/vmware/content/templates/esxi-set-insecure-password.sh.tmpl

Changed print to print() to make the call support python 3

fix(esxi-set-insecure-password): make py3 compat

---

cmds/vmware/content/bootenvs/esxi_700-15843807_hpe.yaml

Updated SHA to match the sha of the ISO in the s3 bucket.
Fixes: #226

fix(vmware): SHA256 was wrong on hpe 7 bootenv

---

cmds/certs/content/._Documentation.meta

placeholder doc added for consistency with other plugins.

fix(cert-plugin): missing metadata doc

---

cmds/bios/content/params/bios-target-configuration-compose.yml
cmds/bios/content/tasks/bios-configure.yml

By setting the bios-target-configuration-compose flag to true,
the system will attempt to merge the bios-target-configuration
parameter into a single value.  This allows for layered options
that can be added for regional or machine specific data.

feat(bios): allow for composable bios-target-configurations

---

cmds/vmware/content/workflows/esxi-install.yaml

In vSphere 7.0.0 in some cases, the `esxi-rename-datastore` stage will randomly fail on first run.  Second run (eg "restart" workflow after failure), it will always succeed.  Trying to inject a timeout delay does not fix the problem for first run failure.
Moving the Stage after the `esxi-activate-network` Stage does allow it to succeed in those cases it was failing.

fix(vmware): Fix failed 'esxi-rename-datastore'

---

cmds/callback/callback.go
utils/per_id_queue.go

Add a serial-per-id callback mechanism, and rewrite the callback
plugin to use it for callback requests.
This will allow up to 100 in-flight callback requests per machine.
Requests across machines will be handled in parallel, and requests
for each machine will be handled in the order they are recieved.

fix(callback): Queue callback event handling.

---

cmds/vmware/content/tasks/esxi-set-network.yaml

Currently, the task exits silently if `esxi/skip-update-address` is `true` (the default type defined value), which isn't clear why the task exited without doing anything.  This adds a simple print() statement to provide clues as to why the address field was not updated.

enhance(vmware): Msg if update address skipped.

---

cmds/vmware/content/templates/vmware-esxi-selector.tmpl

If the ESXi vendor map is used, and the input value specifies the same `mfg` field more than once, then the Template `vmware-esxi-selector.tmpl` will fail as it has ended up trying to test existence of 2 BootEnvs in the drpcli command, like:
`drpcli bootenvs show esxi_700u1-16850804_rkn_lenovo esxi_700u1-x16850804_rkn_vmware-install`
This fix counts the returned bootenvs and exits with error if more than 1 has been found.

enhance(vmware): Safety check if more than one bootenv returned from vendor map

---

cmds/image-deploy/content/templates/curtin-install.sh.tmpl

- adds a simple function that accepts the error code returned by `curtin-install`, and outputs potentially more helpful debugging text

enhance(image-deploy): Add error output to help operator debug

---

cmds/image-deploy/content/._Prerequisites.meta

Image Deploy now supports ESXi image deployments, but this requires pieces from the `drp-community-content` pack.  This fix adds the Prerequisite on v4.6.0 and newer of the DRPCC content.

fix(image-deploy): Add prerequisites on comm. content version requirement

---

cmds/vmware/content/params/esxi-set-network-protocol-skip-reboot.yaml
cmds/vmware/content/params/esxi-set-network-protocol-skip.yaml
cmds/vmware/content/params/esxi-set-network-protocol.yaml
cmds/vmware/content/stages/esxi-activate-network.yaml
cmds/vmware/content/stages/esxi-set-network-protocol.yaml
cmds/vmware/content/tasks/esxi-set-network-protocol.yaml

Adds ability to enable/disable IP protocol suites in ESXi.  Supports setting values of `both`, `ipv4`, and `ipv6`.  However, note that in `ipv6` mode, the IPv4 protocol will not be disabled, as VMware does not provide the ability to disable it in ESXi.
The change is primarily implemented on the `esxi-activate-network` stage as an additional task.  There is a stand alone Stage for composable integration with other workflows if desired.
WARNING: Protocol changes require a reboot.  This is an ESXi hard requirement, and can not be worked around.  On reboot, it is the operators responsibility to verify in advance that appropriate IP addressing is available after the state change for continued network connectivity.
Testing completed:
* DRP and VMware v4.6.x with ESXi 7.0.0u1 and ESXi 6.7.0u3
* …

enhance(vmware): Add IP protocol selection capability (v46x)

---

cmds/ipmi/content/templates/ipmi-inventory.sh.tmpl

IPMI plugin ipmi-inventory task has a typo calling the quirk(s) template - this fixes the typo to reference the correct template name.  Correct template name is `ipmi-load-quirks.sh.tmpl`.
```
Error encountered:
Log for Job: a19f31bb-6993-4e99-bbc4-86e9dfa0517e
Starting task universal-discover:ipmi-inventory:ipmi-inventory on mach-01
Failed to render actions: : template: ipmi-inventory.sh.tmpl:90:12: executing "ipmi-inventory.sh.tmpl" at <{{template "ipmi-load-quirk.sh.tmpl" .}}>: template "ipmi-load-quirk.sh.tmpl" not defined
Updated job for universal-discover:ipmi-inventory:ipmi-inventory to failed
```

fix(ipmi): fix ipmi-inventory typo template call for quirk(s)

---

cmds/callback/content/tasks/callback-task.yaml

Fixes the callback action to add the missing `callbackDo` for Winders `callback-task` in the powershell script

fix(callback): Fix callback usage on Windows

---

cmds/vmware/embedded/scripts/make-esxi.sh

In generated mode, the ISO was still required to be listed in the ISO_MAP array.  This fix removes that requirement.
_Example usage:_
`make-esxi.sh -g -c -B -o /tmp/output -i /tmp/isos. -s VMware-VMvisor-Installer-7.0.0.update02-17630552.x86_64-DellEMC_Customized-A00.iso`
**(g)** enerated
create full **(c)** ontent pack (not just bootenv and boot.cfg template)
**(B)** undle up the content pack
from **(i)** nput directory /tmp/isos
**(o)** utput to directory /tmp/output
for **(s)** pecific ISO VMware-VMvisor-Installer-7.0.0.update02-17630552.x86_64-DellEMC_Customized-A00.iso

fix(vmware): Fix(ish) make-esxi for Generated mode

---

cmds/vmware/content/params/esxi-drpy-token-duration.yaml
cmds/vmware/content/templates/drpy-agent.conf.tmpl
cmds/vmware/content/templates/esxi-drpy-funcs.py.tmpl
cmds/vmware/content/templates/esxi-drpy-run.py.tmpl
cmds/vmware/content/templates/esxi-install-py3-default.ks.tmpl
cmds/vmware/download-vibs.sh

Enabled drpy to use a config located on vfat
Depends on vmware_tools p/r not open yet.

WIP: fix(vmware): remove vmfs requirement for drpy

---

cmds/vmware/content/params/esxi-regenerate-certificates.yaml
cmds/vmware/content/tasks/esxi-install-certificate.yaml

Adds new Param `esxi/regenerate-certificates`; which if set to `true` will cause the `esxi-install-certificates` task to regenerate the Self Signed certificates for the ESXi host.  The Param is `false` by default.
The existing installation of specified Cert/Key pairs will override the request to regenerate the self signed certificate.

enhance(vmware): Add self-signed cert regeneration

---

cmds/endpoint-exec/content/params/endpoint-exec.user.yaml
cmds/endpoint-exec/endpoint-exec.go

Allow for RS_TOKEN to be set to something besides the superuser token
that the plugin runs as.  You can pick from a token that matches what the
agent would use to run a task, or a token generated with the same access
rights as a specific user.

feat(endpoint-exec): Allow different tokens

---

cmds/vmware/content/stages/esxi-install-certificate.yaml
cmds/vmware/content/tasks/esxi-install-certificate.yaml
cmds/vmware/content/tasks/esxi-set-network.yaml
cmds/vmware/content/templates/esxi-service-verify.sh.tmpl
cmds/vmware/content/templates/esxi-set-network.sh.tmpl

Updates the documentation and `OptionalParams` for the `esxi-install-certificate` task.
Adds a new template `esxi-service-verify.sh.tmpl` which will block/wait until a valid `esxcli` call is completed.  The `esxcli` call requires the Firewall services to open, and the API service of ESXi to be fully up and operational.
This template is intended to primarily be included immediately after a `services.sh restart` call is performed; to block and wait until the services all return to operational state.
There appears to have been several race conditions we'd trigger on occasion, with workflow firing off new tasks (eg running `esxcli` commands) too quickly when the ESXi API services weren't fully up.  This would result in a Workflow failure; and the Runner state would be set to false. …

enhance(vmware): Add API service check / TLS Cert Regen Doc enhance

---

cmds/vmware/content/tasks/esxi-host-thumbprint.yaml

Adds a Task to get the ESXi host SHA1 thumbprint, and save it to the machine Param `esxi/thumbprint-sha1`.  Task should be run from the ESXi host in regular workflow. Requires the esxi-params python code to delete/write the Param on the Machine object.

enhance(vmware): Add ESXi host thumbprint task

---

cmds/bios/bioscfg/cmd.go
cmds/bios/bioscfg/dell-racadm.go
cmds/bios/bioscfg/dell.go
cmds/bios/bioscfg/hp.go
cmds/bios/bioscfg/lenovo.go
cmds/bios/bioscfg/models.go
cmds/bios/bioscfg/none.go
cmds/bios/bioscfg/supermicro.go

Update all the integer handling in BIOS settings to use integers of
unbounded size, and fix a bunch of other linter errors while we are at
it.

fix(bios): Latest supermicro uses very large numbers.

---

cmds/raid/content/params/raid-target-config.yaml
cmds/raid/drp-raid/ssacli.go
cmds/raid/drp-raid/volspec.go
go.sum

Turns out that some RAID controllers report that their NVMe devices are
talking the PCIe protocol instead of NVMe.  Add pcie as a disk protocol
to allow automatic RAID generation to work.
WIP: wait on customer feedback before merging.

fix(RAID): Add support for "pcie" as a disk connection type.

---

cmds/vmware/content/._Documentation.meta
cmds/vmware/embedded/scripts/remove_drpy.py

Adds a script to the embedded files that will remove the drpy agent and firewwall vibs.
The script makes an attempt to cleanup the mess as well by removing config files stored on vfat and vmfs volumes.
Some files it may leave behind in /opt/rackn will disapear after the system is rebooted.

feat(vmware): added script to remove drpy
